(function(h,g){"function"===typeof define&&define.amd?define(["./Decoder","./YUVCanvas"],g):"object"===typeof exports?module.exports=g(require("./Decoder"),require("./YUVCanvas")):h.Player=g(h.Decoder,h.YUVCanvas)})(this,function(h,g){var m=h.nowValue,k=function(a){this._config=a||{};this.render=!0;!1===this._config.render&&(this.render=!1);this.nowValue=m;this._config.workerFile=this._config.workerFile||"Decoder.js";this._config.preserveDrawingBuffer&&(this._config.contextOptions=this._config.contextOptions||
    {},this._config.contextOptions.preserveDrawingBuffer=!0);a="auto";!0===this._config.webgl?a=!0:!1===this._config.webgl&&(a=!1);if("auto"==a){a=!0;try{window.WebGLRenderingContext?document.createElement("canvas").getContext("experimental-webgl",{antialias:!1})||(a=!1):a=!1}catch(b){a=!1}}this.webgl=a;this._config.webgl=a;this.webgl?(this.createCanvasObj=this.createCanvasWebGL,this.renderFrame=this.renderFrameWebGL):(this.createCanvasObj=this.createCanvasRGB,this.renderFrame=this.renderFrameRGB);this._config.size||
(this._config.size={});this._config.size.width=this._config.size.width||160;this._config.size.height=this._config.size.height||90;this.render&&(this.canvasObj=this.createCanvasObj({contextOptions:this._config.contextOptions}),this.canvas=this.canvasObj.canvas);this.domNode=this.canvas},l=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame;k.prototype={base_url:window.location.href.replace(/\\/g,"/").replace(/\/[^\/]*$/,""),WorkerInit:function(){this.WorkerTerminate();
        this.WorkerClearCanvas();if(!this.worker){if(window.bApp){var a=new Blob(["importScripts('"+this.base_url+"/"+this._config.workerFile+"');"],{type:"text/javascript"});this.worker=new Worker(window.URL.createObjectURL(a))}else this.worker=new Worker(this._config.workerFile);this.worker.addEventListener("error",function(a){console.log(a)},!1);this.worker.addEventListener("message",this.WorkerMessage.bind(this),!1);this.worker.postMessage({type:"Broadway.js - Worker init",options:{rgb:!this.webgl,memsize:this.memsize,
                reuseMemory:this._config.reuseMemory?!0:!1}})}window.cancelAnimationFrame(this.frameID);this.frameID=l(this.FrameGL.bind(this))},WorkerClearCanvas:function(){if(this.canvasObj.webGLCanvas){this.bFrameUpdate=!1;var a=this.canvasObj.webGLCanvas.contextGL;a.clear(a.COLOR_BUFFER_BIT);a.clear(a.DEPTH_BUFFER_BIT);a.clear(a.STENCIL_BUFFER_BIT)}else this.canvasObj.ctx&&(this.bFrameUpdate=!1,this.canvasObj.ctx.clearRect(0,0,this.canvasObj.canvas.width,this.canvasObj.canvas.height))},frameID:0,WorkerTerminate:function(){window.cancelAnimationFrame(this.frameID);
        this.worker&&(this.worker.terminate(),this.worker=null)},videoStartPlayingCallback:null,delayFrameCallback:null,WorkerMessage:function(a){void 0!=a.data.videoStartPlaying?this.videoStartPlayingCallback&&this.videoStartPlayingCallback():void 0!=a.data.delayFrame?this.delayFrameCallback&&this.delayFrameCallback(a.data.delayFrame):0==this.bFrameUpdate&&(this.webgl?(a.data.yData=new Uint8Array(a.data.yData),a.data.uData=new Uint8Array(a.data.uData),a.data.vData=new Uint8Array(a.data.vData)):a.data.buf=
        new Uint8Array(a.data.buf),this.updateOptions=a.data,this.bFrameUpdate=!0,this.worker.postMessage({bLock:!0}))},PostMessage:function(a){this.worker&&this.worker.postMessage(a)},bFrameUpdate:!1,updateOptions:null,frameCount:0,FrameGL:function(){if(this.bFrameUpdate){if(this.webgl){var a=this.updateOptions,b=this.canvasObj,c=a.width||b.canvas.width,d=a.height||b.canvas.height;b.canvas.width===c&&b.canvas.height===d&&b.webGLCanvas||(b.canvas.width=c,b.canvas.height=d,c/d>this._config.size.width/this._config.size.height?
        b.canvas.style.width=(c/(d/this._config.size.height*this._config.size.width)*100).toFixed(2)+"%":c/d<this._config.size.width/this._config.size.height&&(b.canvas.style.height=(d/(c/this._config.size.width*this._config.size.height)*100).toFixed(2)+"%"),b.webGLCanvas=new g({canvas:b.canvas,contextOptions:b.contextOptions,width:c,height:d}));b.webGLCanvas.drawNextOutputPicture({yData:a.yData,uData:a.uData,vData:a.vData})}else{a=this.updateOptions;b=this.canvasObj;c=a.width||b.canvas.width;d=a.height||
        b.canvas.height;if(b.canvas.width!==c||b.canvas.height!==d)b.canvas.width=c,b.canvas.height=d,c/d>this._config.size.width/this._config.size.height?b.canvas.style.width=(c/(d/this._config.size.height*this._config.size.width)*100).toFixed(2)+"%":c/d<this._config.size.width/this._config.size.height&&(b.canvas.style.height=(d/(c/this._config.size.width*this._config.size.height)*100).toFixed(2)+"%"),b.ctx=b.canvas.getContext("2d"),b.imgData=b.ctx.createImageData(c,d);var e=b.ctx,f=b.imgData;e||(b.ctx=
        b.canvas.getContext("2d"),e=b.ctx,b.imgData=e.createImageData(c,d),f=b.imgData);f.data.set(a.buf);e.putImageData(f,0,0)}this.worker.postMessage({bLock:!1});this.bFrameUpdate=!1}this.frameID=l(this.FrameGL.bind(this))},onPictureDecoded:function(a,b,c,d){},recycleMemory:function(a){},createCanvasWebGL:function(a){var b=this._createBasicCanvasObj(a);b.contextOptions=a.contextOptions;return b},createCanvasRGB:function(a){return this._createBasicCanvasObj(a)},_createBasicCanvasObj:function(a){a=a||{};
        var b={},c=a.width;c||(c=this._config.size.width);a=a.height;a||(a=this._config.size.height);b.canvas=document.createElement("canvas");b.canvas.width=c;b.canvas.height=a;b.canvas.style.width="100%";b.canvas.style.height="100%";b.canvas.style.background="rgba(255,255,255,0)";return b},renderFrameWebGL:function(a){var b=a.canvasObj,c=a.width||b.canvas.width,d=a.height||b.canvas.height;b.canvas.width===c&&b.canvas.height===d&&b.webGLCanvas||(b.canvas.width=c,b.canvas.height=d,b.webGLCanvas=new g({canvas:b.canvas,
        contextOptions:b.contextOptions,width:c,height:d}));var e=c*d;c=c/2*(d/2);b.webGLCanvas.drawNextOutputPicture({yData:a.data.subarray(0,e),uData:a.data.subarray(e,e+c),vData:a.data.subarray(e+c,e+c+c)});this.recycleMemory(a.data)},renderFrameRGB:function(a){var b=a.canvasObj,c=a.width||b.canvas.width,d=a.height||b.canvas.height;if(b.canvas.width!==c||b.canvas.height!==d)b.canvas.width=c,b.canvas.height=d;var e=b.ctx,f=b.imgData;e||(b.ctx=b.canvas.getContext("2d"),e=b.ctx,b.imgData=e.createImageData(c,
        d),f=b.imgData);f.data.set(a.data);e.putImageData(f,0,0);this.recycleMemory(a.data)}};return k});